Manish chart mail
srans-admin/nest-server pull request #14
Opened 2019-12-24 14:42 UTC by Manish-Srans

Check My Code.. Scheduler is not implemented right now. Today Night I'll Implement.

2019-12-24 15:09 UTC, srans-admin requested changes

2019-12-24 15:09 UTC, srans-admin commented on src/main/java/com/srans/nestserver/model/Bed.java
> +		this.position = "";
Why u changed N to empty here?

2019-12-24 15:09 UTC, srans-admin commented on src/main/java/com/srans/nestserver/model/Bed.java
> +		return alloted;
Can you check Booking Bed functionality disturbed with this?

2019-12-24 15:09 UTC, srans-admin commented on src/main/java/com/srans/nestserver/model/User.java
> +		private String emailAddress;
Why is this bean, only for sending email, why do we need seperate bean?

2019-12-24 15:09 UTC, srans-admin commented on src/main/java/com/srans/nestserver/service/MailService.java
> +
Man! I hope just copy pasted code, check what is our requirement, accordingly code, u need to send email to the tenant after registration, it means send email with all the info of tenant with nice template and use as part of the body itself , no attachment required, in your code I don't see from TenantControler you have called this service to send email with logic of sending tenant information which includes name, phone, email, etc along with booked hostel, floor, room, bed information.

2019-12-26 19:11 UTC, srans-admin commented
I dont see any new updates from you yet

2019-12-27 04:16 UTC, srans-admin requested changes
You have not replied to my comments and you don't understand the requirement properly it looks.

2019-12-27 17:50 UTC, Manish-Srans commented
Ram here : I dont see any improvements in this PR, hence closing this and gnererated in seperate PR, with genreic implementions on email

2019-12-27 17:50 UTC, closed without merging